# Generated by Django 5.0.7 on 2024-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('websocket_url', models.URLField()),
                ('websocket_port', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(related_name='game_sessions', to='transcendence.player')),
            ],
        ),
    ]
