# Generated by Django 5.0.7 on 2024-08-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='players_connected',
            field=models.ManyToManyField(related_name='game_sessions_connected', to='transcendence.player'),
        ),
    ]
