version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:hoseoson
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - /home/hoseoson/data/DB:/var/lib/mysql
    networks:
      - docker-network
    restart: always


networks:
  docker-network:
    driver: bridge