version: '3'

services:
  mariadb:
    container_name: mariadb
    # image: mariadb:hoseoson
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - /home/hoseoson/data/DB:/var/lib/mysql
    networks:
      - docker-network
    restart: on-failure

  wordpress:
    container_name: wordpress
    # image: wordpress:hoseoson
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - /home/hoseoson/data/wordpress:/var/www/html
    networks:
      - docker-network
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    # image: nginx:hoseoson
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - /home/hoseoson/data/wordpress:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress

networks:
  docker-network:
    driver: bridge
