version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data:
