version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:hoseoson
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress:hoseoson
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx:hoseoson
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress

networks:
  inception:

volumes:
  wp:
    driver: local
    driver_opts:
      device: /home/hoseoson/data/wp
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: /home/hoseoson/data/db
      o: bind
      type: none