version: '3'

services:
  nginx:
    image: nginx:42
    build: ./requirements/nginx
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - wordpress

  mariadb:
    image: mariadb:42
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    image: wordpress:42
    build: ./requirements/wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data:
