version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:42
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - docker_network

  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker_network

  wordpress:
    container_name: wordpress
    image: wordpress:42
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose: 
      - "9000"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker_network

volumes:
  mariadb_data:
  wordpress_data:

networks:
  docker_network:
    driver: bridge